version: '3.8'

services:
  mongo_db:
    image: mongo
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  train_ticket_app:
    build: .
    container_name: train_ticket_app
    restart: always
    depends_on:
      - mongo_db
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo_db
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=irctc_database
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
